### ISSUE TITLE
Error: https://registry.npmjs.org/@tailwindcss%2fcapacitor: Not found

### ISSUE THREAD

**Issue by vesper8** [Cap-go/tailwind-capacitor#3]
Excited to use this new plugin that was just announced in the Capgo Discord.

`yarn add @tailwindcss/capacitor --save --dev`

I tried installing it and I guess it hasn't been added to the registry yet?

**Comment by riderx** [comment]
Sorry, the doc was wrong, the good name is `tailwind-capacitor`
